// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPN_9BFW71ksGfM1jAupYq1r90eD16VA',
    appId: '1:643311868556:android:ebd97f1fa3be77ec6779a9',
    messagingSenderId: '643311868556',
    projectId: 'wedvision-10723',
    storageBucket: 'wedvision-10723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIcBzVfYYjQ_FoMjoxGHj8VsErd24qyg',
    appId: '1:643311868556:ios:932ac967093676b16779a9',
    messagingSenderId: '643311868556',
    projectId: 'wedvision-10723',
    storageBucket: 'wedvision-10723.appspot.com',
    iosBundleId: 'com.example.wedvision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtho2rWVoGmgkV22Qhh6RBQIuWwhwFL-Y',
    appId: '1:643311868556:web:a4c0a573420f7a106779a9',
    messagingSenderId: '643311868556',
    projectId: 'wedvision-10723',
    authDomain: 'wedvision-10723.firebaseapp.com',
    storageBucket: 'wedvision-10723.appspot.com',
  );
}
